---
ratings:
  paths:
  - "**.php"
checks:
  file-lines:
    enabled: true
    config:
      threshold: 500
  method-complexity:
    enabled: true
    config:
      threshold: 10
  method-count:
    enabled: true
    config:
      threshold: 50
  method-lines:
    config:
      threshold: 75

